mits-gossau/web-components-toolbox

- src/es/components/molecules/pictureText/default-/default-.html
- src/es/components/molecules/pictureWithPicture/default-/default-.html
fix(pictureText): fix h3 tag to h2 tag
fix(pictureWithPicture): fix h3 tag to h2 tag and add missing closing tags
> fix(pictureText, pictureWithPicture): fix h3 tag to h2 tag

- src/es/components/atoms/iframe/Iframe.js
- src/es/components/molecules/form/Form.js
Introduce an new attribute to realize YouTube videos in portrait mode.
Ticket
[MUTOBOTEAM-1999](https://jira.migros.net/browse/MUTOBOTEAM-1999)
(makes https://github.com/mits-gossau/web-components-toolbox-alnatura/pull/14 obsolete)
> feat(Iframe.js): add keep-aspect-ratio attribute for video portrait mode [MUTOBOTEAM-1999]

- docs/Template.html
- src/es/components/molecules/navigation/Navigation.js
- src/es/components/organisms/header/Header.js
- src/es/components/organisms/header/nav-right-/nav-right-.css
- src/es/components/organisms/header/nav-right-/nav-right-.html
Template.html extended to support outer html
navigation new custom variable
> navigation new template nav-right-

- src/es/components/molecules/navigation/Navigation.js
introduce new variable `--a-link-content-spacing-custom-no-scroll`
> fix(Navigation.js): update spacing

- src/es/components/molecules/product/Product.js
i has jez im backend so umbaue dasses die aktuell sproch usliist, und ["slugs"] nüme lieferet nurno direkt de richtig im ["slug"]
> change slugs.fr to slug

- src/es/components/molecules/form/Form.js
Änderung ist kompatibel mit existierenden Formulare, u.a. Alnatura
> style(Form.js): change selector for .umbraco-forms-field class to :host form > div

- docs/TemplateMigrosPro.html
- src/es/components/atoms/basket/Basket.js
- src/es/components/atoms/iconMdx/IconMdx.js
- src/es/components/atoms/userProfile/UserProfile.js
- src/es/components/atoms/userProfile/default-/default-.css
- src/es/components/molecules/productList/ProductList.js
newly using mdx icon component
productList flex item fix
> new template at toolbox due to inflexibility

- src/es/components/molecules/tabs/Tabs.js
- src/es/components/molecules/tabs/default-/default-.html
style(Tabs.js): add style for tab navigation links
refactor(default-.html): update tab navigation and content
feat(default-.html): add link to external website for "Mes Tickets" tab
> fix(Tabs.js): add check for anchor tag before adding click event listener to tabs

- src/es/components/atoms/button/action-/action-.css
feat(button.css): add custom variables for button action background color and hover background color
feat(button.css): add custom variables for button action color and hover color
fix(button.css): fix missing newline at end of file
> chore(button.css): update button action styles

- src/es/components/molecules/tabs/Tabs.js
- src/es/components/molecules/tabs/default-/default-.html
refactor(default-.html): update data-tab attribute values to match tab names
> refactor(Tabs.js): refactor code to set active tab based on URL parameter

- src/es/components/molecules/productList/ProductList.js
refactor(ProductList.js): update styles for system notification component
fix(ProductList.js): fix color and width of svg in system notification component
fix(ProductList.js): update description text and add translation for system notification component
> refactor(ProductList.js): change error notification to info notification when user is not logged in

- src/es/components/atoms/input/Input.js
- src/es/components/atoms/select/Select.js
- src/es/components/molecules/simpleForm/SimpleForm.js
fix(Select.js):IOS_height
fix(Input.js):Expose line-height
> feature(SimpleForm.js):grecaptcha

- src/es/components/atoms/select/Select.js
- src/es/components/molecules/simpleForm/SimpleForm.js
- src/es/components/molecules/simpleForm/default-/default-.css
- src/es/components/organisms/grid/Grid.js
feature(SimpleForm.js):CaptchaMessage and appear disappear feature(Grid.js):auto-fill and auto-fit by attribute
> fix(Select.js):customizable css props

- src/es/components/molecules/dialog/left-slide-in-/left-slide-in-.css
- src/es/components/molecules/dialog/left-slide-in-/left-slide-in-.html
style(left-slide-in-.css): set width to 100% for dialog content container
style(left-slide-in-.html): wrap dialog content in a div for better structure
> style(left-slide-in-.css): add flexbox layout to dialog container

- src/es/components/atoms/button/Button.js
- src/es/components/molecules/dialog/left-slide-in-/left-slide-in-.html
fix(Button.js): add conditional pointer-events style based on 'no-pointer-events' attribute
fix(left-slide-in-.html): add 'no-pointer-events' attribute to close and show-modal buttons
> fix(Button.js): add conditional cursor style based on 'no-pointer-events' attribute

- src/es/components/organisms/header/default-/default-.css
> added --header-default-justify-content-custom

- src/es/components/atoms/menuIcon/MenuIcon.js
- src/es/components/molecules/dialog/Dialog.js
- src/es/components/molecules/dialog/left-slide-in-/left-slide-in-.css
fix/(Dialog.js): attach event on open and close components separately
fix/(Dialog.js): don't rely on default bg color "canvas"
feature/(left-slide-in-.css): extend props through var access
> fix/(MenuIcon.js): only set id when no other id is already set

- index.html
- src/es/components/atoms/button/Button.js
- src/es/components/atoms/button/transparent-/transparent-.css
- src/es/components/atoms/button/transparent-/transparent-.html
- src/es/components/atoms/button/transparent-/transparent-.js
feat(index.html): add "transparent-" button page and plain link
fix(Button.js): add case for fetching transparent button CSS
feat(button): add transparent button styles in CSS file
feat(button): create HTML file for transparent button component
feat(button): add transparent button component for demo purposes
> feat(button): add transparent button component for demo purposes

- src/es/components/atoms/hotspot/Hotspot.js
added --hotspot-width variable because of faulty behaviour when content-width is set
> changed hotspot width

- src/es/components/organisms/footer/Footer.js
fix(footer.js): fix type checking issue with ts-ignore comments
> style(footer.js): add custom alignment properties for footer links and copyright section

- src/es/components/molecules/multiLevelNavigation/delica-/delica-.css
- src/es/components/molecules/tabs/Tabs.js
- src/es/components/organisms/header/Header.js
Refactoring, Bugfixies: Bugfixes Tabsjs, HeaderJs on Menu Icon open scroll to top, small changes delica nav css for dynamic height
> Refactoring, Bugfixies: Bugfixes Tabsjs, HeaderJs on Menu Icon open scroll to top, small changes delica nav css for dynamic height

- src/es/components/molecules/simpleForm/default-/default-.css
style(simpleForm/default-.css): add font style for input, select, textarea, and div elements in simple form
> style(simpleForm/default-.css): add styles for label and input element in simpleform

- src/es/components/organisms/grid/2columns-content-stage-/2columns-content-stage-.css
style(grid): add styling for image inside aside element in 2columns-content-stage grid
style(grid): remove conditional display of aside element when image-src attribute is not present
> feat(2columns-content-stage-.css): improve image handling in color stage [MIDUWEB-816]

- src/css/style.css
- src/es/components/molecules/simpleForm/SimpleForm.js
- src/es/components/molecules/simpleForm/miduweb-/miduweb-.css
style(css): remove unused styles for form p and form hr
> feat(SimpleForm.js): add support for loading miduweb specific CSS file

- src/es/components/molecules/form/Form.js
Only merge with https://github.com/mits-gossau/web-components-toolbox-klubschule/pull/169
> MIDUWEB-760: Added Styling rule for Checkout component

- src/es/components/atoms/button/category-/category-.css
added hyphens:auto for alnatura: https://jira.migros.net/browse/MUTOBOTEAM-2781
> added hyphens auto to aButton Category for alnatura

- src/es/components/molecules/multiLevelNavigation/delica-/delica-.css
BIGFIX: Delica navigation header MUTOBOTEAM-2836
> BIGFIX: Delica navigation header MUTOBOTEAM-2836

- src/es/components/organisms/body/Body.js
@Weedshaker @schmidt1024:
Can we introduce these two css classes here? I constantly need to set these values and we want to avoid inline styles.
> feat: full-width an no-margin classes for o-body

- src/es/components/atoms/input/Input.js
moved answer event listener outside conditions
> tied up event listeners order and condition

- src/es/components/molecules/dialog/left-slide-in-/left-slide-in-.css
> fix: erase display flex to fix major performance issue

- src/es/components/atoms/button/Button.js
- src/es/components/atoms/button/search-/search-.css
- src/es/components/atoms/button/search-/search-.html
- src/es/components/atoms/button/search-/search-.js
feat(button): add styles for search button component in search-.css
feat(button): add search button component with different configurations and demo scripts
> feat(Button.js): add case for 'button-search-' to fetch button search CSS file

- src/es/components/molecules/multiLevelNavigation/delica-/delica-.css
These are only changes for the delica namespace.
> UPDATE: Changes Delica.css for Multilevelnav

- src/es/components/organisms/grid/Grid.js
- src/es/components/organisms/grid/x-columns-/x-columns-.css.js
- src/es/components/organisms/grid/x-columns-/x-columns-.html
feat(grid): add CSS styles for grid columns and responsive breakpoints
feat(grid): add x-columns-.html file to components/organisms/grid directory
> refactor(Grid.js): add case for 'grid-x-' in fetchCSS method

- src/es/components/prototypes/Anchor.js
feat(Anchor.js): add event listener for clicking on hash links to trigger anchor scroll functionality
> refactor(Anchor.js): add logic to prevent multiple rapid clicks on anchor elements

- src/es/components/atoms/picture/Picture.js
- src/es/components/atoms/picture/icon-/icon-.css
- src/es/components/molecules/carouselTwo/CarouselTwo.js
- src/es/components/molecules/carouselTwo/default-/default-.css
- src/es/components/molecules/dialog/default-/default-.css
- m-carousel: attribute "smaller-arrows" that makes the arrows in the carousel smaller (with the variable --arrow-nav-size-small)
- a-picture: new namespace for icon in product teaser
- m-dialog: variables for adjusting border and border-radius
<br>
[Pull Request Product Teaser](https://github.com/mits-gossau/web-components-toolbox-cafe-royal/pull/9)
[Ticket](https://jira.migros.net/browse/MUTOBOTEAM-2933)
> changes for cr-m-product-teaser

- src/es/components/atoms/picture/Picture.js
- src/es/components/atoms/picture/custom-product-teaser-fullsize-/custom-product-teaser-fullsize-.css
- src/es/components/atoms/picture/custom-product-teaser-tileview-/custom-product-teaser-tileview-.css
- namespace for images in Tileview
- namespace for image in Fullsize View
> added custom product teaser a-picture namespaces
